"""Rebuild the reviewed Phase 0 JSON seed. Does not change an existing SQLite DB."""
import json
from pathlib import Path

# ID, names, muscles, equipment, pattern, level, unilateral, reps, cues, mistakes, alternatives.
ROWS = [
    ("goblet_squat", "Goblet Squat", "Sentadilla goblet", "quads glutes", "core", "dumbbells", "squat", "beginner", False, 8, 12,
     "Hold the dumbbell at your chest; sit down between your hips, then stand with feet planted.", "Sostén la mancuerna frente al pecho; baja entre las caderas y sube con los pies apoyados.", "Heels lifting or knees collapsing inward.", "Levantar los talones o dejar que las rodillas caigan hacia dentro.", "sumo_squat reverse_lunge"),
    ("db_rdl_001", "Dumbbell Romanian Deadlift", "Peso muerto rumano con mancuernas", "hamstrings glutes", "erectors", "dumbbells", "hinge", "beginner_intermediate", False, 8, 12,
     "Keep knees softly bent; push hips back with weights close to legs, then stand tall.", "Flexiona ligeramente las rodillas; lleva las caderas atrás con las pesas cerca de las piernas y vuelve a subir.", "Rounding the back or turning the hinge into a squat.", "Redondear la espalda o convertir el movimiento en una sentadilla.", "db_deadlift single_leg_rdl"),
    ("bulgarian_split_squat", "Bulgarian Split Squat", "Sentadilla búlgara", "quads glutes", "hamstrings core", "dumbbells bench", "lunge", "intermediate", True, 8, 12,
     "Rest the rear foot on a stable bench; lower under control and push through the front foot. Repeat each side.", "Apoya el pie trasero en un banco estable; baja con control y empuja con el pie delantero. Repite por lado.", "Pushing mainly with the rear leg or losing balance.", "Empujar principalmente con la pierna trasera o perder el equilibrio.", "reverse_lunge step_up"),
    ("reverse_lunge", "Dumbbell Reverse Lunge", "Zancada hacia atrás con mancuernas", "glutes quads", "hamstrings core", "dumbbells", "lunge", "beginner_intermediate", True, 8, 12,
     "Step one foot back, lower both knees, then drive through the front foot to return. Repeat each side.", "Da un paso atrás, flexiona ambas rodillas y empuja con el pie delantero para volver. Repite por lado.", "Taking a very narrow step or bouncing off the rear foot.", "Dar un paso demasiado estrecho o impulsarse con el pie trasero.", "walking_lunge goblet_squat"),
    ("walking_lunge", "Dumbbell Walking Lunge", "Zancadas caminando con mancuernas", "quads glutes", "hamstrings core", "dumbbells", "lunge", "intermediate", True, 8, 12,
     "Use a clear walkway; step forward, lower with control and bring the rear leg through. Count reps per side.", "Usa un pasillo libre; avanza, baja con control y lleva la pierna trasera adelante. Cuenta repeticiones por lado.", "Rushing steps or letting the front knee collapse inward.", "Apurar los pasos o dejar que la rodilla delantera caiga hacia dentro.", "reverse_lunge bulgarian_split_squat"),
    ("step_up", "Dumbbell Step-Up", "Subida al escalón con mancuernas", "quads glutes", "calves core", "dumbbells step", "lunge", "beginner_intermediate", True, 8, 12,
     "Place the whole foot on a stable low step; stand using the leading leg and lower slowly. Repeat each side.", "Apoya todo el pie en un escalón bajo y estable; sube con esa pierna y baja despacio. Repite por lado.", "Jumping from the floor or using an unstable platform.", "Saltar desde el suelo o usar una plataforma inestable.", "reverse_lunge goblet_squat"),
    ("hip_thrust", "Dumbbell Hip Thrust", "Empuje de cadera con mancuerna", "glutes", "hamstrings core", "dumbbells bench", "bridge", "beginner_intermediate", False, 10, 15,
     "Support upper back on a stable bench and secure a padded weight across hips; raise hips without arching the back.", "Apoya la espalda alta en un banco estable y sujeta la pesa acolchada sobre las caderas; eleva sin arquear la espalda.", "Overextending the lower back or letting the weight roll.", "Arquear demasiado la zona lumbar o dejar rodar la pesa.", "glute_bridge db_rdl_001"),
    ("glute_bridge", "Dumbbell Glute Bridge", "Puente de glúteos con mancuerna", "glutes", "hamstrings core", "dumbbells", "bridge", "beginner", False, 10, 15,
     "Lie with knees bent and feet planted; secure the weight over hips, lift hips and lower slowly.", "Acuéstate con rodillas flexionadas y pies apoyados; sujeta la pesa sobre las caderas, eleva y baja despacio.", "Pushing through toes or arching the lower back.", "Empujar con las puntas de los pies o arquear la zona lumbar.", "hip_thrust db_rdl_001"),
    ("sumo_squat", "Dumbbell Sumo Squat", "Sentadilla sumo con mancuerna", "quads glutes", "core", "dumbbells", "squat", "beginner", False, 8, 12,
     "Take a comfortable wide stance with toes slightly out; lower the weight between legs and stand.", "Separa los pies cómodamente con puntas ligeramente hacia fuera; baja la pesa entre las piernas y sube.", "Forcing an excessively wide stance or rounding the back.", "Forzar una postura demasiado amplia o redondear la espalda.", "goblet_squat db_deadlift"),
    ("single_leg_rdl", "Single-Leg Romanian Deadlift", "Peso muerto rumano a una pierna", "hamstrings glutes", "core erectors", "dumbbells", "hinge", "intermediate", True, 8, 12,
     "Balance on one softly bent leg; hinge while extending the other leg back, keeping hips square. Repeat each side.", "Apóyate en una pierna ligeramente flexionada; inclina el torso llevando la otra atrás y mantén las caderas alineadas. Repite por lado.", "Rotating the hips open or reaching too far down.", "Girar las caderas hacia fuera o bajar más allá del control.", "db_rdl_001 db_deadlift"),
    ("db_deadlift", "Dumbbell Deadlift", "Peso muerto con mancuernas", "glutes hamstrings", "quads erectors", "dumbbells", "hinge", "beginner_intermediate", False, 8, 12,
     "Hold weights beside legs; bend hips and knees within a controlled range, then push the floor away to stand.", "Sostén las pesas junto a las piernas; flexiona caderas y rodillas con control y empuja el suelo para subir.", "Rounding the back to reach the floor or jerking the weights.", "Redondear la espalda para tocar el suelo o tirar bruscamente de las pesas.", "db_rdl_001 sumo_squat"),
    ("bench_press", "Dumbbell Bench Press", "Press de banca con mancuernas", "chest", "triceps shoulders", "dumbbells bench", "horizontal_push", "beginner_intermediate", False, 8, 12,
     "Lie on a stable bench with feet planted; lower weights beside chest and press up with wrists stacked.", "Acuéstate en un banco estable con pies apoyados; baja las pesas junto al pecho y empuja manteniendo las muñecas alineadas.", "Bouncing at the bottom or flaring elbows excessively.", "Rebotar abajo o abrir excesivamente los codos.", "incline_press"),
    ("barbell_bench_press", "Barbell Bench Press", "Press de banca con barra", "chest", "triceps shoulders", "barbell bench", "horizontal_push", "beginner_intermediate", False, 6, 10,
     "Lie on a stable bench with eyes under the bar; lower it toward the mid-chest with control and press up without bouncing.", "Acuéstate en un banco estable con los ojos bajo la barra; bájala hacia el centro del pecho con control y empuja sin rebotar.", "Uncontrolled bar path or lifting the hips from the bench.", "Trayectoria sin control o levantar las caderas del banco.", "bench_press incline_press"),
    ("incline_press", "Incline Dumbbell Press", "Press inclinado con mancuernas", "chest", "shoulders triceps", "dumbbells bench", "horizontal_push", "beginner_intermediate", False, 8, 12,
     "Set an adjustable bench to a low incline; lower weights beside the upper chest and press smoothly.", "Ajusta un banco regulable a una inclinación baja; baja las pesas junto al pecho superior y empuja con control.", "Using a steep incline or bending wrists backward.", "Usar demasiada inclinación o doblar las muñecas hacia atrás.", "bench_press shoulder_press"),
    ("shoulder_press", "Dumbbell Shoulder Press", "Press de hombros con mancuernas", "shoulders", "triceps core", "dumbbells", "vertical_push", "beginner_intermediate", False, 8, 12,
     "Stand tall with weights at shoulder height; press overhead within a comfortable range and lower slowly.", "Mantente erguida con pesas a la altura de los hombros; empuja arriba en un rango cómodo y baja despacio.", "Leaning backward or shrugging through discomfort.", "Inclinarse hacia atrás o encoger los hombros con molestia.", "lateral_raise incline_press"),
    ("lateral_raise", "Dumbbell Lateral Raise", "Elevación lateral con mancuernas", "shoulders", "upper_back", "dumbbells", "isolation", "beginner", False, 10, 15,
     "With soft elbows, lift light weights out to the sides to about shoulder height and lower with control.", "Con codos ligeramente flexionados, eleva pesas ligeras a los lados hasta los hombros y baja con control.", "Swinging the torso or shrugging the weights upward.", "Balancear el torso o subir las pesas encogiendo los hombros.", "shoulder_press rear_delt_fly"),
    ("rear_delt_fly", "Dumbbell Rear Delt Fly", "Apertura posterior con mancuernas", "shoulders upper_back", "core", "dumbbells", "horizontal_pull", "beginner_intermediate", False, 10, 15,
     "Hinge at the hips with a steady back; open softly bent arms out to the sides, then lower.", "Inclina el torso desde las caderas con espalda estable; abre los brazos ligeramente flexionados y baja.", "Jerking heavy weights or rounding the back.", "Tirar de pesas demasiado pesadas o redondear la espalda.", "chest_supported_row one_arm_row"),
    ("one_arm_row", "One-Arm Dumbbell Row", "Remo con mancuerna a una mano", "lats upper_back", "biceps core", "dumbbells bench", "horizontal_pull", "beginner", True, 8, 12,
     "Support one hand on a stable bench; pull the weight toward the hip with a steady torso. Repeat each side.", "Apoya una mano en un banco estable; lleva la pesa hacia la cadera sin girar el torso. Repite por lado.", "Twisting to lift the weight or shrugging the shoulder.", "Girar para levantar la pesa o encoger el hombro.", "chest_supported_row rear_delt_fly"),
    ("chest_supported_row", "Chest-Supported Dumbbell Row", "Remo con mancuernas y pecho apoyado", "upper_back lats", "biceps shoulders", "dumbbells bench", "horizontal_pull", "beginner", False, 8, 12,
     "Rest chest on an inclined adjustable bench with feet braced; pull elbows back and lower smoothly.", "Apoya el pecho en un banco regulable inclinado con pies firmes; lleva los codos atrás y baja con control.", "Lifting the chest off the pad or jerking the weights.", "Separar el pecho del apoyo o tirar bruscamente de las pesas.", "one_arm_row rear_delt_fly"),
    ("pullover", "Dumbbell Pullover", "Pullover con mancuerna", "lats chest", "triceps core", "dumbbells bench", "pullover", "intermediate", False, 8, 12,
     "Lie lengthwise on a bench; hold one secure dumbbell above chest and lower behind the head only within comfortable shoulder motion.", "Acuéstate a lo largo del banco; sujeta una mancuerna sobre el pecho y baja detrás de la cabeza solo en un rango cómodo.", "Lowering too far or arching the ribs upward.", "Bajar demasiado o arquear el torso levantando las costillas.", "one_arm_row bench_press"),
    ("biceps_curl", "Dumbbell Biceps Curl", "Curl de bíceps con mancuernas", "biceps", "forearms", "dumbbells", "isolation", "beginner", False, 10, 15,
     "Keep elbows near the torso and palms forward; curl the weights and lower without swinging.", "Mantén los codos junto al torso y palmas al frente; flexiona los brazos y baja sin balancearte.", "Swinging the body or moving elbows far forward.", "Balancear el cuerpo o adelantar demasiado los codos.", "hammer_curl"),
    ("hammer_curl", "Hammer Curl", "Curl martillo", "biceps forearms", "", "dumbbells", "isolation", "beginner", False, 10, 15,
     "Keep palms facing inward and elbows close; curl the weights while keeping wrists neutral.", "Mantén las palmas hacia dentro y codos cerca; flexiona los brazos con muñecas neutras.", "Bending wrists or using momentum.", "Doblar las muñecas o usar impulso.", "biceps_curl"),
    ("triceps_extension", "Overhead Dumbbell Triceps Extension", "Extensión de tríceps sobre la cabeza", "triceps", "core shoulders", "dumbbells", "isolation", "beginner_intermediate", False, 10, 15,
     "Secure one dumbbell overhead with both hands; bend elbows to lower behind the head, then extend smoothly.", "Sujeta una mancuerna arriba con ambas manos; flexiona los codos para bajar detrás de la cabeza y extiende con control.", "Arching the back or letting the weight slip in the hands.", "Arquear la espalda o dejar que la pesa resbale entre las manos.", "bench_press shoulder_press"),
    ("farmer_carry", "Dumbbell Farmer Carry", "Paseo del granjero con mancuernas", "forearms core", "upper_back glutes", "dumbbells", "carry", "beginner", False, 20, 30,
     "Hold weights at your sides and walk with short controlled steps along a clear path. Count total steps per set.", "Sostén pesas a los lados y camina con pasos cortos y controlados por un camino libre. Cuenta los pasos totales por serie.", "Leaning sideways or rushing with loose grip.", "Inclinarse a un lado o apurarse con agarre flojo.", "russian_twist"),
    ("russian_twist", "Dumbbell Russian Twist", "Giro ruso con mancuerna", "core", "shoulders", "dumbbells", "rotation", "intermediate", True, 8, 12,
     "Sit with heels supported and hold a light weight near the chest; rotate the torso gently side to side. Count each side.", "Siéntate con talones apoyados y una pesa ligera cerca del pecho; gira suavemente el torso a cada lado. Cuenta por lado.", "Rounding the back or forcing large fast twists.", "Redondear la espalda o forzar giros amplios y rápidos.", "farmer_carry"),
]


def build():
    catalog = []
    for row in ROWS:
        id, en, es, primary, secondary, equipment, pattern, difficulty, unilateral, lo, hi, cue_en, cue_es, mistake_en, mistake_es, alternatives = row
        catalog.append(dict(id=id, name=en, display_name_es=es, primary_muscles=primary.split(), secondary_muscles=secondary.split(), equipment=equipment.split(), movement_pattern=pattern, difficulty=difficulty, unilateral=unilateral, default_sets=3, rep_min=lo, rep_max=hi, prescription_unit="steps" if id == "farmer_carry" else "reps", video=dict(type="mp4", uri=None, angles=["side", "front"] if id in {"goblet_squat", "db_rdl_001", "bulgarian_split_squat", "reverse_lunge", "single_leg_rdl"} else ["three_quarter"]), instructions_en=[cue_en], instructions_es=[cue_es], common_mistakes_en=[mistake_en], common_mistakes_es=[mistake_es], alternatives=alternatives.split(), enabled=True))
    target = Path(__file__).parent / "app" / "data" / "exercises.json"
    target.parent.mkdir(exist_ok=True)
    target.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build()
